### ISSUE TITLE
'fat' mode throwing java.lang.ClassNotFoundException

### ISSUE THREAD

**Issue by brunojcm** [thorntail/thorntail#1190]
**Describe the bug**
I've just set up a project using thorntail v4 based on https://docs.thorntail.io/4.0.0-SNAPSHOT/ and some blog posts and it is falling to launch on the dist build.

Maven build outputs as follows:

```
[INFO] --- thorntail-maven-plugin:4.0.0-SNAPSHOT:package (default) @ kmdb-ws ---
[INFO] Processing: kmdb-ws
[INFO] Using detected main() from com.visagio.internal.kmdb.ws.rest.Main
[INFO] mode: fat
[INFO] format: jar
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  10.956 s
[INFO] Finished at: 2018-12-24T19:53:32+08:00
[INFO] ------------------------------------------------------------------------
```

Trying to run, that's what is happening:
```
brunojcm-macbook:kmdb-ws bruno.medeiros$ java -jar ./target/kmdb-ws-bin.jar
Exception in thread "main" java.lang.ClassNotFoundException: com.visagio.internal.kmdb.ws.rest.Main
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:466)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:566)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499)
	at bin.Run.mainClass(Run.java:176)
	at bin.Run.runMain(Run.java:180)
	at bin.Run.run(Run.java:52)
	at bin.Run.main(Run.java:42)
```

If I change it to `thin`, `dir`, run `mvn clean package`, everything works fine:

```
[INFO] --- thorntail-maven-plugin:4.0.0-SNAPSHOT:package (default) @ kmdb-ws ---
[INFO] Processing: kmdb-ws
[INFO] Using detected main() from com.visagio.internal.kmdb.ws.rest.Main
[INFO] mode: thin
[INFO] format: dir
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  10.875 s
[INFO] Finished at: 2018-12-24T20:05:56+08:00
[INFO] ------------------------------------------------------------------------
brunojcm-macbook:kmdb-ws bruno.medeiros$ ./target/kmdb-ws-bin/bin/run.sh
APP does not exist
classes exists
Using classes/ dir
INFO  : Mon. Dec. 24 20:06:01 AWST 2018 [io.thorntail.kernel] THORN-000001: Thorntail - version 4.0.0-SNAPSHOT
INFO  : Mon. Dec. 24 20:06:01 AWST 2018 [io.thorntail.kernel] THORN-000010: Thorntail starting
```

**To Reproduce**
1. Create a thorntail project using lastest 4.x branch
2. set `mode=fat`, `format=jar`
3. run `mvn clean package`
4. `java -jar ./target/app-bin.jar`

**Expected behavior**
`java -jar` should work.

**Desktop (please complete the following information):**
 - OS: macOS 11.14

**Comment by kenfinnigan** [comment]
Can you share what you have in `com.visagio.internal.kmdb.ws.rest.Main` as for v4 we don't expect users to be creating their own Main class

**Comment by brunojcm** [comment]
@kenfinnigan, nothing special, in fact, I just created mine because I couldn't find another one. As I'm migrating from 2.x, I must have forgotten an artifact. What's the main function we should be using?

**Comment by kenfinnigan** [comment]
You shouldn't need to specify one, the plugin will automatically choose `Swarm` as the main class
