### ISSUE TITLE
Error starting thorntail with custom-handler in subsystem logging and javaagent

### ISSUE THREAD

**Issue by hendimarcos** [thorntail/thorntail#1225]
Hello friends,

I'm getting an error when starting thorntail with a custom-handler configured in subsystem logging, but only occurs when I use a javaagent like prometheus.

Caused by: java.lang.NoClassDefFoundError: org/jboss/modules/ModuleLoader

This error already occurs when we only use wildfly, but it has two parameters that we pass in the initialization that makes it work.

  -Dmodule.path=${WILDFLY_HOME}/modules
  -Xbootclasspath/p:${WILDFLY_HOME}/jboss-modules.jar

Described in this comment: https://stackoverflow.com/questions/49330032/wildfly-java-lang-noclassdeffounderror-org-jboss-modules-moduleloader-when-usin#comment92660781_49365818 **(tested)**

With thorntail I do not know how to configure! I have already tried adding jboss-module.jar jar or bootstrap-2.3.0.Final.jar but errors occur. I also do not know how to configure the parameter -Dmodule.path

**To Reproduce**

I am attaching a simple project to reproduce the behavior
[example.zip](https://github.com/thorntail/thorntail/files/2834640/example.zip)

Run:

1. mvn clean install
1. cd run
1. java -Xbootclasspath/p:jboss-logmanager-2.1.5.Final.jar:wildfly-common-1.4.0.Final.jar -javaagent:jmx_prometheus_javaagent-0.11.0.jar=8180:wildfly-10.yaml -Djava.util.logging.manager=org.jboss.logmanager.LogManager -Djboss.modules.system.pkgs=org.jboss.byteman,org.jboss.logmanager -Xms1024m -Xmx2048m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Dswarm.bind.address=127.0.0.1 -Dlogging.configuration=file://${PWD}/logging.properties -Xdebug -XX:ErrorFile=./java_error.log -Dlog4j.defaultInitOverride=false -jar ../target/example-0.0.1-SNAPSHOT-thorntail.jar

**Expected behavior**

The same behavior if I execute the command:

- java -Xms1024m -Xmx2048m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Dswarm.bind.address=127.0.0.1 -Dlogging.configuration=file://${PWD}/logging.properties -Xdebug -XX:ErrorFile=./java_error.log -Dlog4j.defaultInitOverride=false -jar ../target/example-0.0.1-SNAPSHOT-thorntail.jar

or 

- java -Xbootclasspath/p:jboss-logmanager-2.1.5.Final.jar:wildfly-common-1.4.0.Final.jar -javaagent:jmx_prometheus_javaagent-0.11.0.jar=8180:wildfly-10.yaml -Djava.util.logging.manager=org.jboss.logmanager.LogManager -Djboss.modules.system.pkgs=org.jboss.byteman,org.jboss.logmanager -Xms1024m -Xmx2048m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m -Djava.net.preferIPv4Stack=true -Dswarm.bind.address=127.0.0.1 -Dlogging.configuration=file://${PWD}/logging.properties -Xdebug -XX:ErrorFile=./java_error.log -Dlog4j.defaultInitOverride=false -jar ../target/example-0.0.1-SNAPSHOT-thorntail.jar **(without custom-handler do sentry in project-defaults.yml)**

**Desktop (please complete the following information):**
 - OS: Linux Fedora 29
 - Thorntail 2.2.0.Final or 2.3.0.Final

**Stacktrace(s)**

```
    ("subsystem" => "logging"),
    ("custom-handler" => "SENTRY")
]): java.lang.IllegalArgumentException: Failed to load module "io.sentry" for handler "SENTRY"
	at org.jboss.logmanager.config.AbstractPropertyConfiguration.<init>(AbstractPropertyConfiguration.java:65)
	at org.jboss.logmanager.config.HandlerConfigurationImpl.<init>(HandlerConfigurationImpl.java:51)
	at org.jboss.logmanager.config.LogContextConfigurationImpl.addHandlerConfiguration(LogContextConfigurationImpl.java:143)
	at org.jboss.as.logging.logmanager.ConfigurationPersistence.addHandlerConfiguration(ConfigurationPersistence.java:187)
	at org.jboss.as.logging.handlers.HandlerOperations$HandlerAddOperationStepHandler.createHandlerConfiguration(HandlerOperations.java:287)
	at org.jboss.as.logging.handlers.HandlerOperations$HandlerAddOperationStepHandler.performRuntime(HandlerOperations.java:204)
	at org.jboss.as.logging.LoggingOperations$LoggingAddOperationStepHandler.performRuntime(LoggingOperations.java:185)
	at org.jboss.as.controller.AbstractAddStepHandler.performRuntime(AbstractAddStepHandler.java:338)
	at org.jboss.as.controller.AbstractAddStepHandler$1.execute(AbstractAddStepHandler.java:159)
	at org.jboss.as.controller.AbstractOperationContext.executeStep(AbstractOperationContext.java:999)
	at org.jboss.as.controller.AbstractOperationContext.processStages(AbstractOperationContext.java:743)
	at org.jboss.as.controller.AbstractOperationContext.executeOperation(AbstractOperationContext.java:467)
	at org.jboss.as.controller.OperationContextImpl.executeOperation(OperationContextImpl.java:1411)
	at org.jboss.as.controller.ModelControllerImpl.boot(ModelControllerImpl.java:521)
	at org.jboss.as.controller.AbstractControllerService.boot(AbstractControllerService.java:472)
	at org.jboss.as.controller.AbstractControllerService.boot(AbstractControllerService.java:434)
	at org.jboss.as.server.ServerService.boot(ServerService.java:435)
	at org.jboss.as.server.ServerService.boot(ServerService.java:394)
	at org.jboss.as.controller.AbstractControllerService$1.run(AbstractControllerService.java:374)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoClassDefFoundError: org/jboss/modules/ModuleLoader
	at org.jboss.logmanager.config.AbstractPropertyConfiguration$ModuleFinder.getClassLoader(AbstractPropertyConfiguration.java:556)
	at org.jboss.logmanager.config.AbstractPropertyConfiguration.<init>(AbstractPropertyConfiguration.java:63)
	... 19 more
```

**Comment by Ladicek** [comment]
I recall we've already seen the troubles with the Prometheus JMX Exporter agent, and I don't think we found a way around them.

(We had this kind of troubles with the Jolokia agent, too, and those were fixed in the Jolokia agent.)

Besides, this is about Thorntail v2 and hence belongs to JIRA: https://issues.jboss.org/browse/THORN
