### ISSUE TITLE
there is no dependencies when adding JSF fraction to pom.xml

### ISSUE THREAD

**Issue by miroque** [thorntail/thorntail#1226]
**Absent package javax.faces.\***
There is no package for import when using JSF fraction.

**To Reproduce**
1. add `<dependency>
        <groupId>io.thorntail</groupId>
        <artifactId>jsf</artifactId>
    </dependency>`
2. create class with `import javax.faces.application.FacesMessage'
3. there is no such package

**Expected behavior**
There should be this package

**Additional context**
I asked such question at stackoverflow with such [answer](https://stackoverflow.com/a/54535296/1679702)

**Comment by miroque** [comment]
added 

```
    <!-- https://mvnrepository.com/artifact/javax.faces/javax.faces-api -->
    <dependency>
			<groupId>javax.faces</groupId>
			<artifactId>javax.faces-api</artifactId>
			<version>2.3</version>
			<scope>provided</scope>
    </dependency>
```

Yep, this package insertable, but at `mvn thorntail:run`  I've got this stacktrace  error:
```
2019-02-06 11:46:54,440 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-1) MSC000001: Failed to start service jboss.deployment.unit."phonebook.war".POST_MODULE: org.jboss.msc.service.StartException in service jboss.deployment.unit."phonebook.war".POST_MODULE: WFLYSRV0153: Failed to process phase POST_MODULE of deployment "phonebook.war"
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:151)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1738)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.execute(ServiceControllerImpl.java:1700)
	at org.jboss.msc.service.ServiceControllerImpl$ControllerTask.run(ServiceControllerImpl.java:1558)
	at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
	at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1985)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1487)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1364)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.jboss.as.server.deployment.DeploymentUnitProcessingException: java.lang.ClassNotFoundException: javax.faces.webapp.FacesServlet from [Module "deployment.phonebook.war" from Service Module Loader]
	at org.jboss.as.jaxrs.deployment.JaxrsScanningProcessor.checkDeclaredApplicationClassAsServlet(JaxrsScanningProcessor.java:437)
	at org.jboss.as.jaxrs.deployment.JaxrsScanningProcessor.scanWebDeployment(JaxrsScanningProcessor.java:278)
	at org.jboss.as.jaxrs.deployment.JaxrsScanningProcessor.deploy(JaxrsScanningProcessor.java:109)
	at org.jboss.as.server.deployment.DeploymentUnitPhaseService.start(DeploymentUnitPhaseService.java:144)
	... 8 more
Caused by: java.lang.ClassNotFoundException: javax.faces.webapp.FacesServlet from [Module "deployment.phonebook.war" from Service Module Loader]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:255)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:410)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:398)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:116)
	at org.jboss.as.jaxrs.deployment.JaxrsScanningProcessor.checkDeclaredApplicationClassAsServlet(JaxrsScanningProcessor.java:435)
	... 11 more
```

**Comment by Ladicek** [comment]
This is about Thorntail v2 and hence belongs to JIRA: https://issues.jboss.org/projects/THORN

**Comment by miroque** [comment]
Yes, Thorntail 2.3

**Comment by Ladicek** [comment]
I've just filed https://issues.jboss.org/browse/THORN-2327
